services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=nap'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=spring'
    ports:
      - '3308:3306'
